---
- name: Testing andrewrothstein.dgraph
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'dgraph version'
      ansible.builtin.command: dgraph version
      changed_when: false
      register: dgraph_test_output
    - name: Output from 'dgraph version'
      ansible.builtin.debug:
        msg: '{{ dgraph_test_output.stdout }}'
