---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/dgraph version
    register: dgraph_test_output
  - name: dgraph version
    debug:
      msg: '{{ dgraph_test_output.stdout }}'
