---
- name: Resolving vars for {{ dgraph_app.n }}
  ansible.builtin.include_vars:
    file: app-vars.yml
- name: Check for install in {{ dgraph_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ dgraph_install_exe }}'
  changed_when: false
  register: dgraph_binary
- name: Downloading and installing {{ dgraph_app.n }}
  when: not dgraph_binary.stat.exists
  block:
    - name: Downloading {{ dgraph_url }} to {{ dgraph_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ dgraph_url }}'
        dest: '{{ dgraph_tmp_archive }}'
        mode: '644'
        checksum: '{{ dgraph_checksum }}'
    - name: Mkdir {{ dgraph_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dgraph_install_dir }}'
        mode: '755'
        state: directory
    - name: Installing andrewrothstein.unarchivedepos
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ dgraph_tmp_archive }} to {{ dgraph_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ dgraph_tmp_archive }}'
        dest: '{{ dgraph_install_dir }}'
        creates: '{{ dgraph_install_exe }}'
  always:
    - name: Rm {{ dgraph_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dgraph_tmp_archive }}'
        state: absent
- name: Linking {{ dgraph_link }} to {{ dgraph_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ dgraph_install_exe }}'
    dest: '{{ dgraph_link }}'
    state: link
