---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ dgraph_install_dir }}
  become: yes
  stat:
    path: '{{ dgraph_install_dir }}'
  changed_when: False
  register: dgraph_binary
- when: not dgraph_binary.stat.exists
  block:
    - name: downloading {{ dgraph_url }} to {{ dgraph_tmp_archive }}
      become: yes
      become_user: root
      get_url:
        url: '{{ dgraph_url }}'
        dest: '{{ dgraph_tmp_archive }}'
        mode: 0644
        checksum: '{{ dgraph_checksum }}'
    - name: mkdir {{ dgraph_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ dgraph_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchiving {{ dgraph_tmp_archive }} to {{ dgraph_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ dgraph_tmp_archive }}'
        dest: '{{ dgraph_install_dir }}'
        creates: '{{ dgraph_install_dir }}/dgraph'
  always:
    - name: rm {{ dgraph_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ dgraph_tmp_archive }}'
        state: absent
- name: linking executables in {{ dgraph_install_dir }} to {{ dgraph_parent_install_dir }}/bin
  become: yes
  become_user: root
  with_items: '{{ dgraph_executables }}'
  file:
    src: '{{ dgraph_install_dir }}/{{ item }}'
    dest: '{{ dgraph_parent_install_dir }}/bin/{{ item }}'
    state: link
